/*package ExceptionsCourse.seminar2.hw.Task2;

public class Task2SrcCode {
    public static void main(String[] args) {
        try {
            int d = 0;
            double catchedRes1 = intArray[8] / d;
            System.out.println("catchedRes1 = " + catchedRes1);
         } catch (ArithmeticException e) {
            System.out.println("Catching exception: " + e);
         }
    }
}
*/